import React from "react";
import Head from "next/head";
import style from "../styles/layout.module.css";
import Menu from "../components/menu";
import ShoppingCart from "../components/shoppingCart";
const layout = ({ children, title }) => {
  return (
    <div>
      <Head>
        <title>Café Shop {title ? `| ${title}` : ""}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Menu />
      <div className={style.container}>
        {children}

        <ShoppingCart />
      </div>
    </div>
  );
};

export default layout;
